import type {
  Coupon,
  CustomerProfile,
  PlatformSettings,
  Professional,
  Review,
} from './types';

/**
 * Israeli demo dataset so the marketplace is testable the moment it runs —
 * southern-region pros, believable ratings and history. All of it lives only
 * in the demo store; a configured Supabase project starts clean and gets its
 * own seed from supabase/marketplace-schema.sql + the admin panel.
 */

const gallery = [
  { url: '/lp/equipment.webp', caption: 'לפני', kind: 'before' as const },
  { url: '/lp/equipment-2.webp', caption: 'אחרי', kind: 'after' as const },
];

const created = '2025-03-01T08:00:00.000Z';

export const DEMO_PROS: Professional[] = [
  {
    id: 'pro-alex',
    slug: 'alex-sofa-cleaning',
    fullName: 'אלכס פורמן',
    businessName: 'אלכס ניקוי ספות',
    phone: '050-1234567',
    email: 'alex@example.com',
    city: 'באר שבע',
    bio: 'מנקה ספות ומזרנים מעל 7 שנים. עובד עם חומרים היפואלרגניים, אחריות מלאה על התוצאה.',
    languages: ['he', 'ru'],
    yearsExperience: 7,
    workRadiusKm: 25,
    base: { lat: 31.2444, lng: 34.7965 },
    areaIds: ['beer-sheva', 'ofakim', 'netivot'],
    services: [
      { serviceId: 'sofa-cleaning', priceAgorot: 29900 },
      { serviceId: 'mattress-cleaning', priceAgorot: 19900 },
      { serviceId: 'carpet-cleaning' },
    ],
    gallery,
    status: 'active',
    badges: ['verified_id', 'verified_business', 'top_rated', 'jobs_100'],
    commissionPct: null,
    boost: 20,
    rating: 4.9,
    reviewCount: 137,
    jobCount: 312,
    acceptancePct: 94,
    cancelPct: 1,
    lastJobAt: '2026-09-04T15:00:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-david',
    slug: 'david-clean',
    fullName: 'דוד אזולאי',
    businessName: 'דוד קלין',
    phone: '052-2345678',
    email: 'david@example.com',
    city: 'ערד',
    bio: 'שירותי ניקוי ספות, שטיחים ומזגנים בערד והסביבה. מגיע עם ציוד מקצועי מלא.',
    languages: ['he'],
    yearsExperience: 4,
    workRadiusKm: 35,
    base: { lat: 31.2612, lng: 35.2072 },
    areaIds: ['arad', 'dimona', 'beer-sheva'],
    services: [
      { serviceId: 'sofa-cleaning', priceAgorot: 27900 },
      { serviceId: 'ac-cleaning', priceAgorot: 22900 },
      { serviceId: 'carpet-cleaning' },
    ],
    gallery,
    status: 'active',
    badges: ['verified_id', 'platform_checked'],
    commissionPct: null,
    boost: 0,
    rating: 4.7,
    reviewCount: 58,
    jobCount: 121,
    acceptancePct: 88,
    cancelPct: 3,
    lastJobAt: '2026-09-03T11:00:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-cleanpro',
    slug: 'cleanpro-dimona',
    fullName: 'מקסים ברג',
    businessName: 'CleanPro',
    phone: '053-3456789',
    email: 'cleanpro@example.com',
    city: 'דימונה',
    bio: 'צוות מקצועי לניקוי ספות ומזרנים. זמינות גבוהה גם בערבים.',
    languages: ['he', 'ru', 'en'],
    yearsExperience: 5,
    workRadiusKm: 40,
    base: { lat: 31.07, lng: 35.03 },
    areaIds: ['dimona', 'arad', 'beer-sheva'],
    services: [
      { serviceId: 'sofa-cleaning', priceAgorot: 25900 },
      { serviceId: 'mattress-cleaning', priceAgorot: 17900 },
    ],
    gallery,
    status: 'active',
    badges: ['verified_id'],
    commissionPct: null,
    boost: 0,
    rating: 4.6,
    reviewCount: 41,
    jobCount: 96,
    acceptancePct: 91,
    cancelPct: 2,
    lastJobAt: '2026-09-02T18:30:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-sapir',
    slug: 'sapir-fresh',
    fullName: 'ספיר לוי',
    businessName: 'Fresh ניקיון ורעננות',
    phone: '054-4567890',
    email: 'sapir@example.com',
    city: 'באר שבע',
    bio: 'מתמחה בניקוי מזרנים וספות לבתים עם ילדים ובעלי חיים. חומרים טבעיים בלבד.',
    languages: ['he', 'en'],
    yearsExperience: 3,
    workRadiusKm: 20,
    base: { lat: 31.262, lng: 34.7805 },
    areaIds: ['beer-sheva'],
    services: [
      { serviceId: 'sofa-cleaning', priceAgorot: 31900 },
      { serviceId: 'mattress-cleaning', priceAgorot: 21900 },
    ],
    gallery,
    status: 'active',
    badges: ['verified_id', 'platform_checked'],
    commissionPct: null,
    boost: 0,
    rating: 4.8,
    reviewCount: 29,
    jobCount: 64,
    acceptancePct: 96,
    cancelPct: 0,
    lastJobAt: '2026-09-04T09:00:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-kobi',
    slug: 'kobi-air',
    fullName: 'קובי מלכה',
    businessName: 'קובי מיזוג ואוויר נקי',
    phone: '050-5678901',
    email: 'kobi@example.com',
    city: 'אשקלון',
    bio: 'טכנאי מיזוג מוסמך — ניקוי וחיטוי מזגנים עיליים ומיני-מרכזיים.',
    languages: ['he'],
    yearsExperience: 9,
    workRadiusKm: 30,
    base: { lat: 31.6655, lng: 34.5715 },
    areaIds: ['ashkelon', 'ashdod'],
    services: [{ serviceId: 'ac-cleaning', priceAgorot: 24900 }],
    gallery,
    status: 'active',
    badges: ['verified_id', 'verified_business', 'jobs_100'],
    commissionPct: null,
    boost: 0,
    rating: 4.9,
    reviewCount: 112,
    jobCount: 245,
    acceptancePct: 90,
    cancelPct: 1,
    lastJobAt: '2026-09-04T13:00:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-nikita',
    slug: 'nikita-clean-service',
    fullName: 'ניקיטה וולקוב',
    businessName: 'Nikita Clean Service',
    phone: '058-6789012',
    email: 'nikita@example.com',
    city: 'אשדוד',
    bio: 'ניקוי ספות, שטיחים וריפודי רכב. שירות מהיר ומחירים הוגנים.',
    languages: ['ru', 'he'],
    yearsExperience: 2,
    workRadiusKm: 25,
    base: { lat: 31.8, lng: 34.65 },
    areaIds: ['ashdod', 'ashkelon'],
    services: [
      { serviceId: 'sofa-cleaning', priceAgorot: 23900 },
      { serviceId: 'car-upholstery', priceAgorot: 24900 },
    ],
    gallery,
    status: 'active',
    badges: ['verified_id'],
    commissionPct: null,
    boost: 0,
    rating: 4.4,
    reviewCount: 17,
    jobCount: 38,
    acceptancePct: 82,
    cancelPct: 5,
    lastJobAt: '2026-08-30T16:00:00.000Z',
    isDemo: true,
    createdAt: created,
  },
  {
    id: 'pro-pending',
    slug: 'shirly-shine',
    fullName: 'שירלי כהן',
    businessName: 'Shine שירלי',
    phone: '053-7890123',
    email: 'shirly@example.com',
    city: 'נתיבות',
    bio: 'חדשה בפלטפורמה — ניקוי ספות וכיסאות.',
    languages: ['he'],
    yearsExperience: 1,
    workRadiusKm: 15,
    base: { lat: 31.4223, lng: 34.5886 },
    areaIds: ['netivot', 'ofakim'],
    services: [{ serviceId: 'sofa-cleaning' }, { serviceId: 'chairs-cleaning' }],
    gallery: [],
    status: 'pending', // shows up in the admin approval queue
    badges: [],
    commissionPct: null,
    boost: 0,
    rating: 0,
    reviewCount: 0,
    jobCount: 0,
    acceptancePct: 100,
    cancelPct: 0,
    lastJobAt: null,
    isDemo: true,
    createdAt: '2026-09-04T10:00:00.000Z',
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1', bookingId: 'seed-b1', professionalId: 'pro-alex', customerId: 'seed-c1',
    customerName: 'מיכל ב.', serviceId: 'sofa-cleaning', quality: 5, punctuality: 5, service: 5, price: 4,
    text: 'הספה חזרה להיות כמו חדשה! אלכס הגיע בזמן, עבד נקי והריח נעלם לגמרי.',
    createdAt: '2026-08-21T17:30:00.000Z',
  },
  {
    id: 'rev-2', bookingId: 'seed-b2', professionalId: 'pro-alex', customerId: 'seed-c2',
    customerName: 'יוסי ק.', serviceId: 'mattress-cleaning', quality: 5, punctuality: 4, service: 5, price: 5,
    text: 'מקצוען אמיתי. הסביר על כל שלב והמזרנים יצאו מדהים.',
    createdAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'rev-3', bookingId: 'seed-b3', professionalId: 'pro-david', customerId: 'seed-c3',
    customerName: 'אורית ש.', serviceId: 'sofa-cleaning', quality: 5, punctuality: 5, service: 4, price: 4,
    text: 'הגיע לערד תוך חצי שעה, עבודה יסודית ומחיר הוגן.',
    createdAt: '2026-08-28T10:00:00.000Z',
  },
  {
    id: 'rev-4', bookingId: 'seed-b4', professionalId: 'pro-cleanpro', customerId: 'seed-c4',
    customerName: 'רוסלן ג.', serviceId: 'sofa-cleaning', quality: 4, punctuality: 5, service: 5, price: 5,
    text: 'Отличная работа, приехали вечером как договаривались.',
    createdAt: '2026-08-25T19:00:00.000Z',
  },
  {
    id: 'rev-5', bookingId: 'seed-b5', professionalId: 'pro-kobi', customerId: 'seed-c5',
    customerName: 'נועה ל.', serviceId: 'ac-cleaning', quality: 5, punctuality: 5, service: 5, price: 4,
    text: 'המזגן מריח נקי והקירור השתפר פלאים. ממליצה בחום!',
    createdAt: '2026-08-19T14:00:00.000Z',
  },
  {
    id: 'rev-6', bookingId: 'seed-b6', professionalId: 'pro-sapir', customerId: 'seed-c6',
    customerName: 'דנה מ.', serviceId: 'mattress-cleaning', quality: 5, punctuality: 5, service: 5, price: 4,
    text: 'עדינה, מקצועית, והכי חשוב — בלי כימיקלים חזקים. הילדים ישנו כמו מלכים.',
    createdAt: '2026-09-01T20:00:00.000Z',
  },
];

export const DEMO_COUPONS: Coupon[] = [
  {
    code: 'WELCOME20',
    percentOff: 20,
    amountOffAgorot: null,
    serviceId: null,
    areaId: null,
    newCustomersOnly: true,
    expiresAt: null,
    maxRedemptions: null,
    redemptions: 14,
    active: true,
  },
  {
    code: 'SOFA50',
    percentOff: null,
    amountOffAgorot: 5000,
    serviceId: 'sofa-cleaning',
    areaId: 'beer-sheva',
    newCustomersOnly: false,
    expiresAt: '2026-12-31T22:00:00.000Z',
    maxRedemptions: 100,
    redemptions: 3,
    active: true,
  },
];

export const DEMO_CUSTOMER: CustomerProfile = {
  id: 'demo-customer',
  fullName: 'לקוח דמו',
  phone: '050-0000000',
  email: 'demo@example.com',
  language: 'he',
  creditAgorot: 3000,
  referralCode: 'DEMO30',
  favorites: ['pro-alex'],
  blocked: false,
  createdAt: created,
};

export const DEFAULT_SETTINGS: PlatformSettings = {
  businessModel: 'commission',
  commissionPct: 15,
  leadFeeAgorot: 3000,
  subscriptionTiers: [
    { id: 'basic', name: 'Basic', priceAgorot: 9900 },
    { id: 'pro', name: 'Pro', priceAgorot: 19900 },
    { id: 'premium', name: 'Premium', priceAgorot: 34900 },
  ],
  paymentMethods: [
    { id: 'cash', label: 'מזומן בסיום', enabled: true },
    { id: 'card', label: 'כרטיס אשראי', enabled: true },
    { id: 'prepaid', label: 'תשלום מראש', enabled: false },
    { id: 'deposit', label: 'פיקדון', enabled: false },
  ],
  dispatchTtlSeconds: 30,
  dispatchMaxOffers: 6,
  dynamicPricing: {
    enabled: false,
    rushMultiplier: 1.1,
    weekendMultiplier: 1.15,
    lowSupplyMultiplier: 1.2,
  },
  simulationEnabled: true,
};
